version: "3.9"

services:
  app1:
    build: .
    image: rand-line
    environment:
      SYMBOL: "*"
      MIN_LEN: 5
      MAX_LEN: 10
      DELAY: 1

  app2:
    build: .
    image: rand-line
    environment:
      SYMBOL: "#"
      MIN_LEN: 8
      MAX_LEN: 15
      DELAY: 2

  app3:
    build: .
    image: rand-line
    environment:
      SYMBOL: "@"
      MIN_LEN: 3
      MAX_LEN: 6
      DELAY: 3
