version: "3.9"

services:
  films1:
    build: .
    image: film-app
    environment:
      MAX_FILMS: 5
      DATA_FILE_PATH: "./films.json"
      PORT: 8080
    ports:
      - "8081:8080"

  films2:
    build: .
    image: film-app
    environment:
      MAX_FILMS: 10
      DATA_FILE_PATH: "./films.json"
      PORT: 8080
    ports:
      - "8082:8080"
